const keysData = [
  [{
    classes: [],
    code: 'Backquote',
    enUpper: '~',
    enLower: '`',
    ruUpper: 'Ё',
    ruLower: 'ё',
  },
  {
    classes: [],
    code: 'Digit1',
    enUpper: '!',
    enLower: '1',
    ruUpper: '!',
    ruLower: '1',
  },
  {
    classes: [],
    code: 'Digit2',
    enUpper: '@',
    enLower: '2',
    ruUpper: '"',
    ruLower: '2',
  },
  {
    classes: [],
    code: 'Digit3',
    enUpper: '#',
    enLower: '3',
    ruUpper: '№',
    ruLower: '3',
  },
  {
    classes: [],
    code: 'Digit4',
    enUpper: '$',
    enLower: '4',
    ruUpper: ';',
    ruLower: '4',
  },
  {
    classes: [],
    code: 'Digit5',
    enUpper: '%',
    enLower: '5',
    ruUpper: '%',
    ruLower: '5',
  },
  {
    classes: [],
    code: 'Digit6',
    enUpper: '^',
    enLower: '6',
    ruUpper: ':',
    ruLower: '6',
  },
  {
    classes: [],
    code: 'Digit7',
    enUpper: '&',
    enLower: '7',
    ruUpper: '?',
    ruLower: '7',
  },
  {
    classes: [],
    code: 'Digit8',
    enUpper: '*',
    enLower: '8',
    ruUpper: '*',
    ruLower: '8',
  },
  {
    classes: [],
    code: 'Digit9',
    enUpper: '(',
    enLower: '9',
    ruUpper: '(',
    ruLower: '9',
  },
  {
    classes: [],
    code: 'Digit0',
    enUpper: ')',
    enLower: '0',
    ruUpper: ')',
    ruLower: '0',
  },
  {
    classes: [],
    code: 'Minus',
    enUpper: '_',
    enLower: '-',
    ruUpper: '_',
    ruLower: '-',
  },
  {
    classes: [],
    code: 'Equal',
    enUpper: '+',
    enLower: '=',
    ruUpper: '+',
    ruLower: '=',
  },
  {
    classes: ['key_double', 'key_darker'],
    code: 'Backspace',
    enUpper: 'Backspace',
    enLower: 'Backspace',
    ruUpper: 'Backspace',
    ruLower: 'Backspace',
  }],
  [{
    classes: ['key_darker'],
    code: 'Tab',
    enUpper: 'Tab',
    enLower: 'Tab',
    ruUpper: 'Tab',
    ruLower: 'Tab',
  },
  {
    classes: [],
    code: 'KeyQ',
    enUpper: 'Q',
    enLower: 'q',
    ruUpper: 'Й',
    ruLower: 'й',
  },
  {
    classes: [],
    code: 'KeyW',
    enUpper: 'W',
    enLower: 'w',
    ruUpper: 'Ц',
    ruLower: 'ц',
  },
  {
    classes: [],
    code: 'KeyE',
    enUpper: 'E',
    enLower: 'e',
    ruUpper: 'У',
    ruLower: 'у',
  },
  {
    classes: [],
    code: 'KeyR',
    enUpper: 'R',
    enLower: 'r',
    ruUpper: 'К',
    ruLower: 'к',
  },
  {
    classes: [],
    code: 'KeyT',
    enUpper: 'T',
    enLower: 't',
    ruUpper: 'Е',
    ruLower: 'е',
  },
  {
    classes: [],
    code: 'KeyY',
    enUpper: 'Y',
    enLower: 'y',
    ruUpper: 'Н',
    ruLower: 'н',
  },
  {
    classes: [],
    code: 'KeyU',
    enUpper: 'U',
    enLower: 'u',
    ruUpper: 'Г',
    ruLower: 'г',
  },
  {
    classes: [],
    code: 'KeyI',
    enUpper: 'I',
    enLower: 'i',
    ruUpper: 'Ш',
    ruLower: 'ш',
  },
  {
    classes: [],
    code: 'KeyO',
    enUpper: 'O',
    enLower: 'o',
    ruUpper: 'Щ',
    ruLower: 'щ',
  },
  {
    classes: [],
    code: 'KeyP',
    enUpper: 'P',
    enLower: 'p',
    ruUpper: 'З',
    ruLower: 'з',
  },
  {
    classes: [],
    code: 'BracketLeft',
    enUpper: '{',
    enLower: '[',
    ruUpper: 'Х',
    ruLower: 'х',
  },
  {
    classes: [],
    code: 'BracketRight',
    enUpper: '}',
    enLower: ']',
    ruUpper: 'Ъ',
    ruLower: 'ъ',
  },
  {
    classes: [],
    code: 'Backslash',
    enUpper: '|',
    enLower: '\\',
    ruUpper: '/',
    ruLower: '\\',
  },
  {
    classes: ['key_darker'],
    code: 'Delete',
    enUpper: 'Del',
    enLower: 'Del',
    ruUpper: 'Del',
    ruLower: 'Del',
  }],
  [{
    classes: ['key_double', 'key_darker'],
    code: 'CapsLock',
    enUpper: 'CapsLock',
    enLower: 'CapsLock',
    ruUpper: 'CapsLock',
    ruLower: 'CapsLock',
  },
  {
    classes: [],
    code: 'KeyA',
    enUpper: 'A',
    enLower: 'a',
    ruUpper: 'Ф',
    ruLower: 'ф',
  },
  {
    classes: [],
    code: 'KeyS',
    enUpper: 'S',
    enLower: 's',
    ruUpper: 'Ы',
    ruLower: 'ы',
  },
  {
    classes: [],
    code: 'KeyD',
    enUpper: 'D',
    enLower: 'd',
    ruUpper: 'В',
    ruLower: 'в',
  },
  {
    classes: [],
    code: 'KeyF',
    enUpper: 'F',
    enLower: 'f',
    ruUpper: 'А',
    ruLower: 'а',
  },
  {
    classes: [],
    code: 'KeyG',
    enUpper: 'G',
    enLower: 'g',
    ruUpper: 'П',
    ruLower: 'п',
  },
  {
    classes: [],
    code: 'KeyH',
    enUpper: 'H',
    enLower: 'h',
    ruUpper: 'Р',
    ruLower: 'р',
  },
  {
    classes: [],
    code: 'KeyJ',
    enUpper: 'J',
    enLower: 'j',
    ruUpper: 'О',
    ruLower: 'о',
  },
  {
    classes: [],
    code: 'KeyK',
    enUpper: 'K',
    enLower: 'k',
    ruUpper: 'Л',
    ruLower: 'л',
  },
  {
    classes: [],
    code: 'KeyL',
    enUpper: 'L',
    enLower: 'l',
    ruUpper: 'Д',
    ruLower: 'д',
  },
  {
    classes: [],
    code: 'Semicolon',
    enUpper: ':',
    enLower: ';',
    ruUpper: 'Ж',
    ruLower: 'ж',
  },
  {
    classes: [],
    code: 'Quote',
    enUpper: '"',
    enLower: "'",
    ruUpper: 'Э',
    ruLower: 'э',
  },
  {
    classes: ['key_double', 'key_darker'],
    code: 'Enter',
    enUpper: 'Enter',
    enLower: 'Enter',
    ruUpper: 'Enter',
    ruLower: 'Enter',
  }],
  [{
    classes: ['key_double', 'key_darker'],
    code: 'ShiftLeft',
    enUpper: 'Shift',
    enLower: 'Shift',
    ruUpper: 'Shift',
    ruLower: 'Shift',
  },
  {
    classes: [],
    code: 'KeyZ',
    enUpper: 'Z',
    enLower: 'z',
    ruUpper: 'Я',
    ruLower: 'я',
  },
  {
    classes: [],
    code: 'KeyX',
    enUpper: 'X',
    enLower: 'x',
    ruUpper: 'Ч',
    ruLower: 'ч',
  },
  {
    classes: [],
    code: 'KeyC',
    enUpper: 'C',
    enLower: 'c',
    ruUpper: 'С',
    ruLower: 'с',
  },
  {
    classes: [],
    code: 'KeyV',
    enUpper: 'V',
    enLower: 'v',
    ruUpper: 'М',
    ruLower: 'м',
  },
  {
    classes: [],
    code: 'KeyB',
    enUpper: 'B',
    enLower: 'b',
    ruUpper: 'И',
    ruLower: 'и',
  },
  {
    classes: [],
    code: 'KeyN',
    enUpper: 'N',
    enLower: 'n',
    ruUpper: 'Т',
    ruLower: 'т',
  },
  {
    classes: [],
    code: 'KeyM',
    enUpper: 'M',
    enLower: 'm',
    ruUpper: 'Ь',
    ruLower: 'ь',
  },
  {
    classes: [],
    code: 'Comma',
    enUpper: '<',
    enLower: ',',
    ruUpper: 'Б',
    ruLower: 'б',
  },
  {
    classes: [],
    code: 'Period',
    enUpper: '>',
    enLower: '.',
    ruUpper: 'Ю',
    ruLower: 'ю',
  },
  {
    classes: [],
    code: 'Slash',
    enUpper: '?',
    enLower: '/',
    ruUpper: ',',
    ruLower: '.',
  },
  {
    classes: ['key_darker'],
    code: 'ArrowUp',
    enUpper: '↑',
    enLower: '↑',
    ruUpper: '↑',
    ruLower: '↑',
  },
  {
    classes: ['key_double', 'key_darker'],
    code: 'ShiftRight',
    enUpper: 'Shift',
    enLower: 'Shift',
    ruUpper: 'Shift',
    ruLower: 'Shift',
  }],
  [{
    classes: ['key_darker'],
    code: 'ControlLeft',
    enUpper: 'Ctrl',
    enLower: 'Ctrl',
    ruUpper: 'Ctrl',
    ruLower: 'Ctrl',
  },
  {
    classes: ['key_darker'],
    code: 'MetaLeft',
    enUpper: 'Win',
    enLower: 'Win',
    ruUpper: 'Win',
    ruLower: 'Win',
  },
  {
    classes: ['key_darker'],
    code: 'AltLeft',
    enUpper: 'Alt',
    enLower: 'Alt',
    ruUpper: 'Alt',
    ruLower: 'Alt',
  },
  {
    classes: ['key_space'],
    code: 'Space',
    enUpper: ' ',
    enLower: ' ',
    ruUpper: ' ',
    ruLower: ' ',
  },
  {
    classes: ['key_darker'],
    code: 'AltRight',
    enUpper: 'Alt',
    enLower: 'Alt',
    ruUpper: 'Alt',
    ruLower: 'Alt',
  },
  {
    classes: ['key_darker'],
    code: 'ArrowLeft',
    enUpper: '←',
    enLower: '←',
    ruUpper: '←',
    ruLower: '←',
  },
  {
    classes: ['key_darker'],
    code: 'ArrowDown',
    enUpper: '↓',
    enLower: '↓',
    ruUpper: '↓',
    ruLower: '↓',
  },
  {
    classes: ['key_darker'],
    code: 'ArrowRight',
    enUpper: '→',
    enLower: '→',
    ruUpper: '→',
    ruLower: '→',
  },
  {
    classes: ['key_darker'],
    code: 'ControlRight',
    enUpper: 'Ctrl',
    enLower: 'Ctrl',
    ruUpper: 'Ctrl',
    ruLower: 'Ctrl',
  }],
];

export default keysData;
