const keysData = [
  [{
    classes: [],
    code: 'Backquote',
    en_upper: '~',
    en_lower: '`',
    ru_upper: 'Ё',
    ru_lower: 'ё',
  },
  {
    classes: [],
    code: 'Digit1',
    en_upper: '!',
    en_lower: '1',
    ru_upper: '!',
    ru_lower: '1',
  },
  {
    classes: [],
    code: 'Digit2',
    en_upper: '@',
    en_lower: '2',
    ru_upper: '"',
    ru_lower: '2',
  },
  {
    classes: [],
    code: 'Digit3',
    en_upper: '#',
    en_lower: '3',
    ru_upper: '№',
    ru_lower: '3',
  },
  {
    classes: [],
    code: 'Digit4',
    en_upper: '$',
    en_lower: '4',
    ru_upper: ';',
    ru_lower: '4',
  },
  {
    classes: [],
    code: 'Digit5',
    en_upper: '%',
    en_lower: '5',
    ru_upper: '%',
    ru_lower: '5',
  },
  {
    classes: [],
    code: 'Digit6',
    en_upper: '^',
    en_lower: '6',
    ru_upper: ':',
    ru_lower: '6',
  },
  {
    classes: [],
    code: 'Digit7',
    en_upper: '&',
    en_lower: '7',
    ru_upper: '?',
    ru_lower: '7',
  },
  {
    classes: [],
    code: 'Digit8',
    en_upper: '*',
    en_lower: '8',
    ru_upper: '*',
    ru_lower: '8',
  },
  {
    classes: [],
    code: 'Digit9',
    en_upper: '(',
    en_lower: '9',
    ru_upper: '(',
    ru_lower: '9',
  },
  {
    classes: [],
    code: 'Digit0',
    en_upper: ')',
    en_lower: '0',
    ru_upper: ')',
    ru_lower: '0',
  },
  {
    classes: [],
    code: 'Minus',
    en_upper: '_',
    en_lower: '-',
    ru_upper: '_',
    ru_lower: '-',
  },
  {
    classes: [],
    code: 'Equal',
    en_upper: '+',
    en_lower: '=',
    ru_upper: '+',
    ru_lower: '=',
  },
  {
    classes: ['key_double'],
    code: 'Backspace',
    en_upper: 'Backspace',
    en_lower: 'Backspace',
    ru_upper: 'Backspace',
    ru_lower: 'Backspace',
  }],
  [{
    classes: [],
    code: 'Tab',
    en_upper: 'Tab',
    en_lower: 'Tab',
    ru_upper: 'Tab',
    ru_lower: 'Tab',
  },
  {
    classes: [],
    code: 'KeyQ',
    en_upper: 'Q',
    en_lower: 'q',
    ru_upper: 'Й',
    ru_lower: 'й',
  },
  {
    classes: [],
    code: 'KeyW',
    en_upper: 'W',
    en_lower: 'w',
    ru_upper: 'Ц',
    ru_lower: 'ц',
  },
  {
    classes: [],
    code: 'KeyE',
    en_upper: 'E',
    en_lower: 'e',
    ru_upper: 'У',
    ru_lower: 'у',
  },
  {
    classes: [],
    code: 'KeyR',
    en_upper: 'R',
    en_lower: 'r',
    ru_upper: 'К',
    ru_lower: 'к',
  },
  {
    classes: [],
    code: 'KeyT',
    en_upper: 'T',
    en_lower: 't',
    ru_upper: 'Е',
    ru_lower: 'е',
  },
  {
    classes: [],
    code: 'KeyY',
    en_upper: 'Y',
    en_lower: 'y',
    ru_upper: 'Н',
    ru_lower: 'н',
  },
  {
    classes: [],
    code: 'KeyU',
    en_upper: 'U',
    en_lower: 'u',
    ru_upper: 'Г',
    ru_lower: 'г',
  },
  {
    classes: [],
    code: 'KeyI',
    en_upper: 'I',
    en_lower: 'i',
    ru_upper: 'Ш',
    ru_lower: 'ш',
  },
  {
    classes: [],
    code: 'KeyO',
    en_upper: 'O',
    en_lower: 'o',
    ru_upper: 'Щ',
    ru_lower: 'щ',
  },
  {
    classes: [],
    code: 'KeyP',
    en_upper: 'P',
    en_lower: 'p',
    ru_upper: 'З',
    ru_lower: 'з',
  },
  {
    classes: [],
    code: 'BracketLeft',
    en_upper: '{',
    en_lower: '[',
    ru_upper: 'Х',
    ru_lower: 'х',
  },
  {
    classes: [],
    code: 'BracketRight',
    en_upper: '}',
    en_lower: ']',
    ru_upper: 'Ъ',
    ru_lower: 'ъ',
  },
  {
    classes: [],
    code: 'Backslash',
    en_upper: '|',
    en_lower: '\\',
    ru_upper: '/',
    ru_lower: '\\',
  },
  {
    classes: [],
    code: 'Delete',
    en_upper: 'Del',
    en_lower: 'Del',
    ru_upper: 'Del',
    ru_lower: 'Del',
  }],
  [{
    classes: ['key_double'],
    code: 'CapsLock',
    en_upper: 'CapsLock',
    en_lower: 'CapsLock',
    ru_upper: 'CapsLock',
    ru_lower: 'CapsLock',
  },
  {
    classes: [],
    code: 'KeyA',
    en_upper: 'A',
    en_lower: 'a',
    ru_upper: 'Ф',
    ru_lower: 'ф',
  },
  {
    classes: [],
    code: 'KeyS',
    en_upper: 'S',
    en_lower: 's',
    ru_upper: 'Ы',
    ru_lower: 'ы',
  },
  {
    classes: [],
    code: 'KeyD',
    en_upper: 'D',
    en_lower: 'd',
    ru_upper: 'В',
    ru_lower: 'в',
  },
  {
    classes: [],
    code: 'KeyF',
    en_upper: 'F',
    en_lower: 'f',
    ru_upper: 'А',
    ru_lower: 'а',
  },
  {
    classes: [],
    code: 'KeyG',
    en_upper: 'G',
    en_lower: 'g',
    ru_upper: 'П',
    ru_lower: 'п',
  },
  {
    classes: [],
    code: 'KeyH',
    en_upper: 'H',
    en_lower: 'h',
    ru_upper: 'Р',
    ru_lower: 'р',
  },
  {
    classes: [],
    code: 'KeyJ',
    en_upper: 'J',
    en_lower: 'j',
    ru_upper: 'О',
    ru_lower: 'о',
  },
  {
    classes: [],
    code: 'KeyK',
    en_upper: 'K',
    en_lower: 'k',
    ru_upper: 'Л',
    ru_lower: 'л',
  },
  {
    classes: [],
    code: 'KeyL',
    en_upper: 'L',
    en_lower: 'l',
    ru_upper: 'Д',
    ru_lower: 'д',
  },
  {
    classes: [],
    code: 'Semicolon',
    en_upper: ':',
    en_lower: ';',
    ru_upper: 'Ж',
    ru_lower: 'ж',
  },
  {
    classes: [],
    code: 'Quote',
    en_upper: '"',
    en_lower: "'",
    ru_upper: 'Э',
    ru_lower: 'э',
  },
  {
    classes: ['key_double'],
    code: 'Enter',
    en_upper: 'Enter',
    en_lower: 'Enter',
    ru_upper: 'Enter',
    ru_lower: 'Enter',
  }],
  [{
    classes: ['key_double'],
    code: 'ShiftLeft',
    en_upper: 'Shift',
    en_lower: 'Shift',
    ru_upper: 'Shift',
    ru_lower: 'Shift',
  },
  {
    classes: [],
    code: 'KeyZ',
    en_upper: 'Z',
    en_lower: 'z',
    ru_upper: 'Я',
    ru_lower: 'я',
  },
  {
    classes: [],
    code: 'KeyX',
    en_upper: 'X',
    en_lower: 'x',
    ru_upper: 'Ч',
    ru_lower: 'ч',
  },
  {
    classes: [],
    code: 'KeyC',
    en_upper: 'C',
    en_lower: 'c',
    ru_upper: 'С',
    ru_lower: 'с',
  },
  {
    classes: [],
    code: 'KeyV',
    en_upper: 'V',
    en_lower: 'v',
    ru_upper: 'М',
    ru_lower: 'м',
  },
  {
    classes: [],
    code: 'KeyB',
    en_upper: 'B',
    en_lower: 'b',
    ru_upper: 'И',
    ru_lower: 'и',
  },
  {
    classes: [],
    code: 'KeyN',
    en_upper: 'N',
    en_lower: 'n',
    ru_upper: 'Т',
    ru_lower: 'т',
  },
  {
    classes: [],
    code: 'KeyM',
    en_upper: 'M',
    en_lower: 'm',
    ru_upper: 'Ь',
    ru_lower: 'ь',
  },
  {
    classes: [],
    code: 'Comma',
    en_upper: '<',
    en_lower: ',',
    ru_upper: 'Б',
    ru_lower: 'б',
  },
  {
    classes: [],
    code: 'Period',
    en_upper: '>',
    en_lower: '.',
    ru_upper: 'Ю',
    ru_lower: 'ю',
  },
  {
    classes: [],
    code: 'Slash',
    en_upper: '?',
    en_lower: '/',
    ru_upper: ',',
    ru_lower: '.',
  },
  {
    classes: [],
    code: 'ArrowUp',
    en_upper: '↑',
    en_lower: '↑',
    ru_upper: '↑',
    ru_lower: '↑',
  },
  {
    classes: ['key_double'],
    code: 'ShiftRight',
    en_upper: 'Shift',
    en_lower: 'Shift',
    ru_upper: 'Shift',
    ru_lower: 'Shift',
  }],
  [{
    classes: [],
    code: 'ControlLeft',
    en_upper: 'Ctrl',
    en_lower: 'Ctrl',
    ru_upper: 'Ctrl',
    ru_lower: 'Ctrl',
  },
  {
    classes: [],
    code: 'MetaLeft',
    en_upper: 'Win',
    en_lower: 'Win',
    ru_upper: 'Win',
    ru_lower: 'Win',
  },
  {
    classes: [],
    code: 'AltLeft',
    en_upper: 'Alt',
    en_lower: 'Alt',
    ru_upper: 'Alt',
    ru_lower: 'Alt',
  },
  {
    classes: ['key_space'],
    code: 'Space',
    en_upper: ' ',
    en_lower: ' ',
    ru_upper: ' ',
    ru_lower: ' ',
  },
  {
    classes: [],
    code: 'AltRight',
    en_upper: 'Alt',
    en_lower: 'Alt',
    ru_upper: 'Alt',
    ru_lower: 'Alt',
  },
  {
    classes: [],
    code: 'ControlRight',
    en_upper: 'Ctrl',
    en_lower: 'Ctrl',
    ru_upper: 'Ctrl',
    ru_lower: 'Ctrl',
  },
  {
    classes: [],
    code: 'ArrowLeft',
    en_upper: '←',
    en_lower: '←',
    ru_upper: '←',
    ru_lower: '←',
  },
  {
    classes: [],
    code: 'ArrowDown',
    en_upper: '↓',
    en_lower: '↓',
    ru_upper: '↓',
    ru_lower: '↓',
  },
  {
    classes: [],
    code: 'ArrowRight',
    en_upper: '→',
    en_lower: '→',
    ru_upper: '→',
    ru_lower: '→',
  }],
];

export default keysData;
